### ISSUE TITLE
BTree KVStore

### ISSUE THREAD

**Issue by alexanderbez** [osmosis-labs/cosmos-sdk#294]
## Description

An argument can be made for the need of a logical binary merkle store that is primary used for state-sync only, i.e. no need for light client proofs.

Theres lots of data we want only state syncable, and not light client provable in blockchains. If you want a state sync only logical store, you can basically make a merkle-ized BTree, but with fan-out factor of 1024, or 1024 * 1024. This is similar to what Dropbox [does](https://www.dropbox.com/developers/reference/content-hash). This provides very low overhead and you get a final hash you can include in the root multi-store.

However, we want to utilize a different physical storage for the underlying DB, such as sqlite as opposed to IAVL. This is to take advantage of performance of such databases and the layout of data in storage that will help aid in various retrieval and storage patterns.

Modules should be able to declare the need to use such a store for various aspects of its state, if not for the entire state. To facilitate this we need to perform the following:

## Tasks

- [ ] Implement a merkle BTree as a `KVStore`
- [ ] Support the ability to provide multiple physical databases in `config.toml`
- [ ] Define extension APIs to allow modules to use and declare separate store types
- [ ] Any changes necessary to the root multistore API
